### ISSUE TITLE
n-ai nevoie de interfata asta. si daca e sa o faci, clasa va fi Impl, nu interfata

### ISSUE THREAD

**Issue by bulzanstefan** [cezarhre/curs23-project#1]
https://github.com/cezarhre/curs23-project/blob/1d5777f811ff2abee5d3f4fefbbb9f510ef169e6/src/main/java/ro/fasttrackit/curs22/homework/curs22homework/model/QuestionsImpl.java#L7

**Comment by cezarhre** [comment]
Am sters clasa.
